import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Provider from "./provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <div
            className="min-h-screen relative bg-fixed bg-center bg-cover"
            style={{
              backgroundImage: "url('/images/mountains.jpg')",
              backgroundAttachment: "fixed",
            }}
          >
            {/* Overlay Gradient */}
            <div className="absolute inset-0 bg-gradient-to-br from-orange-100 via-purple-50 to-blue-100 opacity-20" />

            {/* Content */}
            <div className="relative z-10">
              <Header />
              <main className="container mx-auto px-4 py-8 max-w-2xl">
                {children}
              </main>
            </div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
